# Site settings
title: Andrew Jack
description: Andrew Jack's homepage
url: "https://andrewjack.uk" # the base hostname & protocol for your site

# User settings
username: Andrew Jack
user_description: Android Developer, Cyclist, Sailor
email: me@andrewjack.uk
twitter_username: andr3wjack
github_username:  AndrewJack
linkedin_username:  andr3wjack

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
# links:
#   - title: Home
#     url: /
#   - title: Series
#     url: /series
#   - title: Tags
#     url: /tags
#   - title: About Me
#     url: /about

# exclude my node related stuff
exclude: []
